

var pgErrCode = {
	PG_ERR_Normal: 0,
	PG_ERR_System: 1,
	PG_ERR_BadParam: 2,
	PG_ERR_BadClass: 3,
	PG_ERR_BadMethod: 4,
	PG_ERR_BadObject: 5,
	PG_ERR_BadStatus: 6,
	PG_ERR_BadFile: 7,
	PG_ERR_BadUser: 8,
	PG_ERR_BadPass: 9,
	PG_ERR_NoLogin: 10,
	PG_ERR_Network: 11,
	PG_ERR_Timeout: 12,
	PG_ERR_Reject: 13,
	PG_ERR_Busy: 14,
	PG_ERR_Opened: 15,
	PG_ERR_Closed: 16,
	PG_ERR_Exist: 17,
	PG_ERR_NoExist: 18,
	PG_ERR_NoSpace: 19,
	PG_ERR_BadType: 20,
	PG_ERR_CheckErr: 21,
	PG_ERR_BadServer: 22,
	PG_ERR_BadDomain: 23,   
	PG_ERR_NoDate: 24,   
	PG_ERR_Unknown: 255
};
